x-postgres-common:
  &postgres-common
  image: picasso/pg15-patroni:develop
  env_file:
    - .env
  ports:
    - "5432"
    - "8008"
  environment:
    &postgres-envs
    PATRONI_ETCD3_HOSTS: ${PATRONI_ETCD3_HOSTS}
    PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
    PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
    PATRONI_SCOPE: pg15cluster
    PATRONI_NAMESPACE: ${PATRONI_SCOPE:-pg15cluster}
  entrypoint: ["/usr/local/bin/entrypoint.sh"]
  logging:
    options:
      max-size: "1m"
      max-file: "5"
  depends_on:
    - etcd
  healthcheck:
    test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
    interval: 5s
    timeout: 5s
    retries: 5
  restart: on-failure

x-etcd-common:
  &etcd-common
  image: bitnami/etcd:3.5.16
  restart: unless-stopped
  env_file:
      - .env
  logging:
    options:
      max-size: "1m"
      max-file: "5"
  environment:
    &etcd-envs
    ALLOW_NONE_AUTHENTICATION: yes
    ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
    ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    ETCD_INITIAL_CLUSTER: ${ETCD_INITIAL_CLUSTER}
    ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster
    ETCD_INITIAL_CLUSTER_STATE: new
  ports:
    - "2379"
    - "2380"

services:
  etcd:
    <<: *etcd-common
    hostname: etcd
    container_name: etcd
    environment:
      <<: *etcd-envs
      ETCD_NAME: etcd
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    volumes:
        - etcd-data:/bitnami/etcd

  haproxy:
    image: haproxy:3.0.5-alpine3.20
    hostname: haproxy
    container_name: haproxy
    env_file:
        - .env
    ports:
      - "8404:8404"
      - "6432:6432"
      - "6433:6433"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  pgsql15clu01:
    <<: *postgres-common
    container_name: postgresql-01
    environment:
      <<: *postgres-envs
      PATRONI_NAME: pgsql15clu01
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: pgsql15clu01:5432
    volumes:
      - ./patroni/patroni.yml:/venv/etc/patroni.yml:ro
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro

  pgsql15clu02:
    <<: *postgres-common
    container_name: postgresql-02
    environment:
      <<: *postgres-envs
      PATRONI_NAME: pgsql15clu02
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: pgsql15clu02:5432
    volumes:
      - ./patroni/patroni.yml:/venv/etc/patroni.yml:ro
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro

  pgsql15clu03:
    <<: *postgres-common
    container_name: postgresql-03
    environment:
      <<: *postgres-envs
      PATRONI_NAME: pgsql15clu03
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: pgsql15clu03:5432
    volumes:
      - ./patroni/patroni.yml:/venv/etc/patroni.yml:ro
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
volumes:
    etcd-data:
      driver: local
