---
log:
  format: '%(asctime)s %(levelname)s: %(message)s'
  level: INFO
  trace_level: DEBUG
  dir: /var/log/patroni
  file_size: 10000000
  file_num: 5
  max_queue_size: 1000
  type: plain

etcd3:
  hosts: etcd:2379

bootstrap:
  post_bootstrap: /usr/local/bin/create_users.sh
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_slots: true
      use_pg_rewind: true
      parameters:
        ssl: 'off'
        hot_standby: 'on'
        max_connections: 500
        shared_buffers: 2G
        effective_cache_size: 6G
        work_mem: 128MB
        maintenance_work_mem: 1GB
        log_min_duration_statement: 100ms
        idle_in_transaction_session_timeout: 15s
        shared_preload_libraries: 'pg_stat_statements'
        pg_stat_statements.max: 10000
        pg_stat_statements.track: 'all'
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        max_replication_slots: 20
        max_wal_senders: 20
        max_worker_processes: 8
        track_commit_timestamp: 'off'
        wal_keep_size: 1GB
        wal_level: logical
        archive_mode: 'on'
        archive_command: 'barman-wal-archive backup-api "$HOSTNAME" /var/lib/postgresql/data/%p'
        wal_max_senders: 10
        wal_log_hints: 'on'
        password_encryption: scram-sha-256
        synchronous_commit: 'on'
        synchronous_standby_names: '*'
      recovery_conf:
        restore_command: 'barman-wal-restore backup-api "$HOSTNAME" /var/lib/postgresql/data/pg_wal/%f %p'
      callbacks:
        on_start: |
          chmod 0750 /var/lib/postgresql/data && \
          chmod 0750 /var/lib/postgresql/data/pg_wal
        on_role_change: '/venv/bin/patroni_barman --api-url http://backup-api:7480 config-switch --barman-server backup-api --barman-model ${HOSTNAME} --switch-when promoted'
  initdb:
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

postgresql:
  pgpass: /tmp/pgpass
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/15/bin
  authentication:
    rewind:
      password: rewind
      username: rewind
    replication:
      password: barman
      username: barman
    superuser:
      password: postgres
      username: postgres
  create_replica_methods:
    - barman
    - basebackup
  #  barman:
  #    command: /venv/bin/patroni_barman --api-url http://backup-api:7480 recover
  #    barman-server: backup-api
  #    ssh-command: ssh barman@${HOSTNAME}
  basebackup:
    max-rate: '100M'
    checkpoint: fast
  pg_hba:
    - local   all             all                                   trust
    - host    all             all               0.0.0.0/0           scram-sha-256
    - host    all             all               ::0/0               scram-sha-256
    - host    all             postgres          0.0.0.0/0           scram-sha-256
    - host    all             postgres          ::0/0               scram-sha-256
    #    - host    replication     edw_repl_user     0.0.0.0/0           scram-sha-256
    #    - host    replication     edw_repl_user     ::0/0               scram-sha-256
    - host    replication     barman            0.0.0.0/0           scram-sha-256
    - host    replication     barman            ::0/0               scram-sha-256

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
  noloadbalance: false
  nostream: false
  nosync: false
